# Build the Go Binary.
FROM golang as build_service-api
ENV CGO_ENABLED 0
ARG BUILD_REF

# Copy the source code into the container.
COPY . /service

# Build the service binary.
WORKDIR /service
RUN go build -ldflags "-X main.build=${BUILD_REF}"

# Run the Go Binary in Alpine
FROM alpine
ARG BUILD_DATE
ARG BUILD_REF
COPY --from=build_service-api /service/service /service/service
WORKDIR /service
CMD ["./service"]

LABEL org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.title="service-api" \
      org.opencontainers.image.authors="Nathan Tsao <tw_lala@hotmail.com>" \
      org.opencontainers.image.source="https://github.com/wolftsao/service/app/service-api" \
      org.opencontainers.image.revision="${BUILD_REF}" \
      org.opencontainers.image.vendor="Ardan Labs"